### ISSUE TITLE
Please update to v0.22.0 build 11997575

### ISSUE THREAD

**Issue by rustymunkey** [BrammyS/necesse-docker-server#41]
Hi all!

There is a new update available to version `v0.22.0 build 11997575` (see https://necessegame.com/server/). The currently latest available version for this docker image is for `build 11985542` only. 
I am not able to start the current image with `build 11997575`, I am getting an exception `java.lang.IllegalStateException: Resources not loaded yet`.
However, according to a discussion on the official necesse discord this error should be fixed with the latest release of the game server.

Thanks for all your work, the image has always been working nicely for us!

**Comment by BrammyS** [comment]
Hhmmm that's weird. The images is not being automatically updated.

**Comment by BrammyS** [comment]
Attempted to update the image manually from my phone. Can't test it tho. So please let me know if it's working now!

**Comment by BrammyS** [comment]
Another version has been published. Image has been automatically updated again. Closing the issue.
