### ISSUE TITLE
Server needs updating

### ISSUE THREAD

**Issue by Gasteren** [BrammyS/necesse-docker-server#76]
Not really a bug.

Necesse was updated to version 0.26.0 if not mistaken.
Unable to play on the server until the image gets updated i suppose.

**Comment by BrammyS** [comment]
Seems like the x path to the download url has changed again. So the automatic updater needs to be updated again. However, I'll try to manually update it later tonight.

**Comment by BrammyS** [comment]
You can always make a PR for that as well. Simply look at the past PRs for an example.

**Comment by Gasteren** [comment]
I see, let me see if i can pull and upate the url to https://necessegame.com/content/server/0-26-0-15329744/necesse-server-linux64-0-26-0-15329744.zip

**Comment by Gasteren** [comment]
Pull request send. that should do the trick

**Comment by BrammyS** [comment]
Merged! Please let me works if it works properly.

**Comment by Gasteren** [comment]
![image](https://github.com/user-attachments/assets/9a4b4b35-3355-4a10-99b3-954eb47f2bc6)

Works!
